# Generated by Django 4.2.9 on 2024-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_congé_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Employee'), ('2', 'Manager'), ('3', 'Responsablerh'), ('4', 'Director'), ('5', 'HOD')], default='3', max_length=150),
        ),
    ]
