# Generated by Django 4.2.9 on 2024-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_congé_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
