# Generated by Django 4.2.9 on 2024-08-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_congé_app', '0003_leaverequest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
