# Generated by Django 4.2.9 on 2024-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_congé_app', '0004_leaverequest_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved by Manager', 'Approved by Manager'), ('Rejected by Manager', 'Rejected by Manager'), ('Approved by Responsablerh', 'Approved by Rresponsablerh'), ('Rejected by Responsablerh', 'Rejected by Rresponsablerh')], default='Draft', max_length=50),
        ),
    ]
